export const primeIcons = [
  { label: 'Pasta (portfólio)', value: 'pi pi-briefcase' },
  { label: 'Prédio', value: 'pi pi-building' },
  { label: 'Raios', value: 'pi pi-bolt' },
  { label: 'Nuvem', value: 'pi pi-cloud' },
  { label: 'Computador', value: 'pi pi-desktop' },
  { label: 'Banco de dados', value: 'pi pi-database' },
  { label: 'E-mail', value: 'pi pi-envelope' },
  { label: 'Telefone', value: 'pi pi-phone' },
  { label: 'WhatsApp', value: 'pi pi-whatsapp' },
  { label: 'Usuário', value: 'pi pi-user' },
  { label: 'Usuários', value: 'pi pi-users' },
  { label: 'Calendário', value: 'pi pi-calendar' },
  { label: 'Horário', value: 'pi pi-clock' },
  { label: 'Livro', value: 'pi pi-book' },
  { label: 'Graduação', value: 'pi pi-graduation-cap' },
  { label: 'Moeda', value: 'pi pi-dollar' },
  { label: 'Gráfico', value: 'pi pi-chart-line' },
  { label: 'Mundo', value: 'pi pi-globe' },
  { label: 'Coração', value: 'pi pi-heart' },
  { label: 'Escudo', value: 'pi pi-shield' },
  { label: 'Wi-Fi', value: 'pi pi-wifi' },
  { label: 'Sol', value: 'pi pi-sun' },
  { label: 'Estrela', value: 'pi pi-star' },
  { label: 'Casa', value: 'pi pi-home' },
  { label: 'Sino', value: 'pi pi-bell' },
  { label: 'Concluído', value: 'pi pi-check-circle' },
  { label: 'Informação', value: 'pi pi-info-circle' },
  { label: 'Ajuda', value: 'pi pi-question-circle' },
  { label: 'Arquivo', value: 'pi pi-file' },
  { label: 'Pasta', value: 'pi pi-folder' },
  { label: 'Cadeado', value: 'pi pi-lock' },
  { label: 'Chave', value: 'pi pi-key' },
  { label: 'Moedas', value: 'pi pi-money-bill' },
  { label: 'Carteira', value: 'pi pi-wallet' },
  { label: 'Ingresso', value: 'pi pi-ticket' },
  { label: 'Configurações', value: 'pi pi-cog' },
  { label: 'Lápis', value: 'pi pi-pencil' },
  { label: 'Menu', value: 'pi pi-bars' },
  { label: 'Servidor', value: 'pi pi-server' },
  { label: 'Fones', value: 'pi pi-headphones' },
  { label: 'Mais', value: 'pi pi-plus-circle' },
  { label: 'Atenção', value: 'pi pi-exclamation-triangle' },
  { label: 'Cancelar', value: 'pi pi-times-circle' }
]

export const categoriasServico = [
  'Atendimento',
  'Acadêmico',
  'Saúde',
  'Bem-estar',
  'Carreira',
  'Comunidade',
  'Formação',
  'Direito',
  'Financeiro',
  'TI',
  'Biblioteca',
  'Outros'
]

export const categoriasFaq = [
  'Portal',
  'Acadêmico',
  'Financeiro',
  'Matrícula',
  'TI',
  'Biblioteca',
  'Outros'
]