<template>
<section><PageHeader title="Central de Ajuda" subtitle="CRUD das perguntas frequentes consumidas pelo HelpCenterModal." @add="novo"/>
<DataTable :value="items" paginator :rows="8" class="mt-6 overflow-hidden rounded-2xl border" stripedRows><Column field="titulo" header="Pergunta"/><Column field="categoria" header="Categoria"/><Column field="ordem" header="Ordem"/><Column header="Status"><template #body="{data}"><Tag :value="data.ativo?'Publicado':'Oculto'" :severity="data.ativo?'success':'secondary'"/></template></Column><Column header="Ações"><template #body="{data}"><Button icon="pi pi-pencil" text rounded @click="editar(data)"/><Button icon="pi pi-trash" text rounded severity="danger" @click="excluir(data)"/></template></Column></DataTable>
<Dialog v-model:visible="visible" modal header="Pergunta frequente" class="w-full max-w-2xl"><div class="grid gap-4"><div><label class="label">Pergunta</label><InputText v-model="form.titulo" class="w-full"/></div><div><label class="label">Resposta</label><Textarea v-model="form.resposta" rows="6" class="w-full"/></div><div class="grid grid-cols-1 gap-4 sm:grid-cols-2"><div><label class="label">Categoria</label><Dropdown v-model="form.categoria" :options="categoriasFaq" editable filter placeholder="Selecione ou digite a categoria" class="w-full"/></div><div><label class="label">Ícone PrimeIcons</label><Dropdown v-model="form.icone" :options="primeIcons" optionLabel="label" optionValue="value" filter placeholder="Selecione um ícone" class="w-full"><template #value="{value}"><i :class="value"></i><span class="ml-2 truncate">{{value}}</span></template><template #option="{option}"><i :class="option.value"></i><span class="ml-2">{{option.label}}</span></template></Dropdown></div></div><div class="grid grid-cols-1 gap-4 sm:grid-cols-2"><div><label class="label">Cor do ícone</label><InputText v-model="form.corIcone" class="w-full"/></div><div><label class="label">Ordem</label><InputNumber v-model="form.ordem" class="w-full"/></div></div><div class="flex gap-3"><ToggleSwitch v-model="form.ativo"/><span>Publicado no Portal</span></div></div><template #footer><Button label="Cancelar" text @click="visible=false"/><Button label="Salvar" @click="salvar"/></template></Dialog><ConfirmDialog/><Toast/></section>
</template>
<script setup>
import {ref,onMounted} from 'vue';import {caeApi} from '../services/api';import PageHeader from '../components/PageHeader.vue';import DataTable from 'primevue/datatable';import Column from 'primevue/column';import Button from 'primevue/button';import Dialog from 'primevue/dialog';import InputText from 'primevue/inputtext';import Textarea from 'primevue/textarea';import InputNumber from 'primevue/inputnumber';import ToggleSwitch from 'primevue/toggleswitch';import Tag from 'primevue/tag';import ConfirmDialog from 'primevue/confirmdialog';import Toast from 'primevue/toast';import Dropdown from 'primevue/dropdown';import {useConfirm} from 'primevue/useconfirm';import {useToast} from 'primevue/usetoast';import {primeIcons,categoriasFaq} from '../services/icones'
const items=ref([]),visible=ref(false),editing=ref(null),confirm=useConfirm(),toast=useToast(),form=ref({});const load=async()=>items.value=(await caeApi.faqs.list()).data;const novo=()=>{editing.value=null;form.value={titulo:'',resposta:'',categoria:'Portal',icone:'pi pi-question-circle',corIcone:'#3b82f6',ordem:items.value.length+1,ativo:true};visible.value=true};const editar=x=>{editing.value=x;form.value={...x};visible.value=true};const salvar=async()=>{editing.value?await caeApi.faqs.update(editing.value.id,form.value):await caeApi.faqs.create(form.value);visible.value=false;toast.add({severity:'success',summary:'Salvo',detail:'FAQ atualizada',life:2000});load()};const excluir=x=>confirm.require({message:'Excluir esta FAQ?',header:'Confirmar',accept:async()=>{await caeApi.faqs.remove(x.id);load()}});onMounted(load)
</script><style scoped>.label{display:block;margin-bottom:.35rem;font-size:.875rem;font-weight:600;color:#334155}</style>
