<template>
<section><PageHeader title="Horários de Atendimento" subtitle="Configure os horários mostrados no modal da Central de Atendimento." @add="novo"/>
<DataTable :value="items" class="mt-6 overflow-hidden rounded-2xl border" stripedRows><Column field="diaSemana" header="Dia"/><Column field="horaInicio" header="Início"/><Column field="horaFim" header="Fim"/><Column header="Status"><template #body="{data}"><Tag :value="data.fechado?'Fechado':data.ativo?'Ativo':'Inativo'" :severity="data.fechado?'danger':data.ativo?'success':'secondary'"/></template></Column><Column header="Ações"><template #body="{data}"><Button icon="pi pi-pencil" text rounded @click="editar(data)"/><Button icon="pi pi-trash" text rounded severity="danger" @click="excluir(data)"/></template></Column></DataTable>
<Dialog v-model:visible="visible" modal header="Horário" class="w-full max-w-lg"><div class="grid gap-4"><div><label class="label">Dia</label><InputText v-model="form.diaSemana" class="w-full"/></div><div class="grid grid-cols-2 gap-4"><div><label class="label">Início</label><InputText v-model="form.horaInicio" class="w-full" placeholder="08:00"/></div><div><label class="label">Fim</label><InputText v-model="form.horaFim" class="w-full" placeholder="18:00"/></div></div><div class="flex gap-3"><ToggleSwitch v-model="form.fechado"/><span>Fechado</span></div><div class="flex gap-3"><ToggleSwitch v-model="form.ativo"/><span>Publicado</span></div></div><template #footer><Button label="Cancelar" text @click="visible=false"/><Button label="Salvar" @click="salvar"/></template></Dialog><ConfirmDialog/><Toast/></section>
</template>
<script setup>
import {ref,onMounted} from 'vue';import {caeApi} from '../services/api';import PageHeader from '../components/PageHeader.vue';import DataTable from 'primevue/datatable';import Column from 'primevue/column';import Button from 'primevue/button';import Dialog from 'primevue/dialog';import InputText from 'primevue/inputtext';import ToggleSwitch from 'primevue/toggleswitch';import Tag from 'primevue/tag';import ConfirmDialog from 'primevue/confirmdialog';import Toast from 'primevue/toast';import {useConfirm} from 'primevue/useconfirm';import {useToast} from 'primevue/usetoast'
const items=ref([]),visible=ref(false),editing=ref(null),confirm=useConfirm(),toast=useToast(),form=ref({})
const load=async()=>items.value=(await caeApi.horarios.list()).data;const novo=()=>{editing.value=null;form.value={diaSemana:'',horaInicio:'08:00',horaFim:'18:00',fechado:false,ativo:true,ordem:items.value.length+1};visible.value=true};const editar=x=>{editing.value=x;form.value={...x};visible.value=true};const salvar=async()=>{editing.value?await caeApi.horarios.update(editing.value.id,form.value):await caeApi.horarios.create(form.value);visible.value=false;toast.add({severity:'success',summary:'Salvo',detail:'Horário atualizado',life:2000});load()};const excluir=x=>confirm.require({message:'Excluir este horário?',header:'Confirmar',accept:async()=>{await caeApi.horarios.remove(x.id);load()}});onMounted(load)
</script><style scoped>.label{display:block;margin-bottom:.35rem;font-size:.875rem;font-weight:600;color:#334155}</style>
